#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1595788577                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : ma                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://zitouna.xyz                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Manage your olive squwisser.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Abdelmajid Rajad
your_link                                 : https://zitouna.xyz
your_city                                 : Beni Mellal
email_address                             : abdelmajid.rajad@gmail.com
facebook_username                         :
instagram_username                        :
twitter_username                          : aabdelmajid
github_username                           : abdelmajidrajad
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Manage Grinding
    description                           : Calculate your customer olive weight.
    fontawesome_icon_name                 : mortar-pestle

  - title                                 : Customer Invoice
    description                           : Print an invoice for your customer.
    fontawesome_icon_name                 : file-invoice-dollar

  - title                                 : Know Customers
    description                           : Add new customers.
    fontawesome_icon_name                 : users

  - title                                 : Sale Oil & Olive
    description                           : Sale oil, bottles, olive.
    fontawesome_icon_name                 : shopping-cart

  - title                                 : Pay Team
    description                           : Pay your teams and manage tasks.
    fontawesome_icon_name                 : money-bill-alt

  - title                                 : Message Customer
    description                           : Send Whatsapp or SMS to customers to let them know about grinding tasks.
    fontawesome_icon_name                 : comment

  - title                                 : Customer payments
    description                           : Grab payments from customers.
    fontawesome_icon_name                 : money-check-alt

  - title                                 : Make Purchase
    description                           : Add your purchases to have good insight about oil price.
    fontawesome_icon_name                 : shopping-basket

  - title                                 : Fancy Design
    description                           : Change app design to Dark/Light and choose best app icons.
    fontawesome_icon_name                 : adjust

  - title                                 : Arabic Support
    description                           : Choose arabic language or english and play.
    fontawesome_icon_name                 : language



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : yellow                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
